### PR TITLE
There are no packages to install for OS X.

### PR DESCRIPTION
**Pull request by Sauraus**

### CODE REVIEW

**Comment by tas50** [comment]
There's a linting failure and this needs the DCO signoff, but this looks 👍

**Comment by Sauraus** [comment]
The more concerning issue is how did this get passed any OS X tests, or do we not test on OS X for this cookbook?

**Comment by Sauraus** [comment]
The lint issues are in the spec test recipes, not sure these should be fixed with this PR ?

```
FC005: Avoid repetition of resource declarations: ./spec/recipes/default_spec.rb:4
FC011: Missing README in markdown format: spec/README.md:1
FC016: LWRP does not declare a default action: ./spec/resources/default_spec.rb:1
FC031: Cookbook without metadata file: spec/metadata.rb:1
FC045: Metadata does not contain cookbook name: spec/metadata.rb:1
✔ ~/GitHub.com/ark [macosx|✔] 
```

**Comment by tas50** [comment]
I'll take a look at the failures locally

**Pull request merged**
