### PR TITLE
Support append_env_path property on Windows.

### PR DESCRIPTION
**Pull request by sgtcoolguy**
### Description

Supports usage of the append_env_path property for Windows.

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [X] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

Signed-off-by: Christopher Williams <chris.a.williams@gmail.com>

### CODE REVIEW

**Comment by tas50** [comment]
@sgtcoolguy Can you rebase this?

**Comment by sgtcoolguy** [comment]
OK, rebased to fix conflict.

**Comment by tas50** [comment]
@sgtcoolguy Any chance you can rebase this again. I realize I already had you rebase it. Sorry :(

**Comment by sgtcoolguy** [comment]
@tas50 rebased!

**Pull request merged**
